config/routes.rb
Rails.application.routes.draw do
  root to: 'books#index'

  devise_for :users
  resources :books do
    resources :rentals, only: %i[new create]
  end

  resources :dashboards, only: %i[index]
  resources :rentals, only: %i[destroy]
  resources :profiles, only: %i[index]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :rentals

  validates :title, presence: true
  validates :year, presence: true
  validates :author, presence: true
  validates :overview, presence: true, length: { maximum: 500 }
  validates :genre, presence: true


  include PgSearch::Model
  pg_search_scope :search_by_title_and_author_overview_genre,
    against: [ :title, :author, :overview, :genre ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/rental.rb
class Rental < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validate :start_date, :end_date
  validate :end_date_after_start_date

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    errors.add(:end_date, "Sorry, the ending of your rental must be after the start date") if end_date < start_date
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_many :rentals

  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name photo])
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[show edit update destroy new]
  skip_before_action :authenticate_user!, only: %i[index show]

  def initialize_book
    @user = Book.new
  end

  def index
    @books = Book.all
    if params[:query].present?
      sql_subquery = "title ILIKE :query OR author ILIKE :query OR overview ILIKE :query OR genre ILIKE :query"
      @books = @books.where(sql_subquery, query: "%#{params[:query]}%")
    end
  end

  def show
    @rental = Rental.new

    @existing_rental_dates = @book.rentals.map do |rental|
      {
        from: rental.start_date,
        to: rental.end_date
      }
    end
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    @book.user = current_user
    if @book.save
      redirect_to dashboards_path(current_user), notice: "Your book was successfully created!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @book.update(book_params)
      redirect_to dashboards_path(current_user), notice: "Your book has been succesfully updated!"
    else
      render :edit
    end
  end

  def destroy
    if @book.user == current_user
      @book.destroy
      redirect_to dashboards_path(current_user), status: :see_other
    else
      redirect_to dashboards_path(current_user), notice: "You are not the owner of this book!"
    end
  end

  private

  def set_book
    @book = Book.find(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :author, :year, :overview, :genre)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_user, only: [:show]
  
  def index
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @rentals = @user.rentals
  end


private 

  def set_user
    @user = User.find(params[:id])
  end

  # def user_params
  #   params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :photo)
  # end
end
 

app/controllers/rentals_controller.rb
class RentalsController < ApplicationController
  def new
    @rental = Rental.new
  end

  def create
    @book = Book.find(params[:book_id])
    @rental = Rental.new(rental_params)
    @rental.user = current_user
    @rental.book = @book

    if @book.user == current_user
      redirect_to book_path(@book), notice: "You own this book!"
      return
    end

    if @rental.save
      redirect_to dashboards_path(current_user), notice: "You have successfully rented this book!"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @rental = Rental.find(params[:id])
    if @rental.user == current_user
      @rental.destroy
      redirect_to dashboards_path(current_user), status: :see_other
    else
      redirect_to dashboards_path(current_user), notice: "You are not renting this book!"
    end
  end

  private

  def rental_params
    params.require(:rental).permit(:start_date, :end_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/edit.html.erb
<div class="container py-5">
   <div class="row">
      <div class="col-12 col-md-6 offset-lg-3">
         <div class="bg-white rounded p-3 shadow">
            <h4>Edit book</h4>
            <%= simple_form_for @book do |f| %>
              <%= f.input :title %>
              <%= f.input :year %>
              <%= f.input :author %>
              <%= f.input :overview %>
              <%= f.input :genre %>
              <%= f.submit class: 'btn btn-success' %>
            <% end %>
         </div>
      </div>
   </div>
</div>

app/views/books/index.html.erb
<div class="cover">

  <div class="cover-heading p-5">
    <h1 class="rent">Rent</h1>
    <h1 class="book">Books</h1>
  </div>
</div>
<hr>
<div class="container py-5">
  <div class="d-flex align-align-text-center justify-content-between mb-5">
    <h3
      class="mb-0"
      style="font-family: 'Gill Sans', 'Gill Sans MT', Calibri, 'Trebuchet MS', sans-serif;"
    >Books to Rent</h3>
    <i class="fa-thin fa-books"></i>
    <!-- Add New book : Modal dialog-->
    <button
      type="button"
      class="btn btn-outline-success"
      data-toggle="modal"
      data-target=".bd-example-modal-md">Add a New Book
    </button>

    <div
      class="modal fade bd-example-modal-md"
      tabindex="-1"
      role="dialog"
      aria-labelledby="myLargeModalLabel"
      aria-hidden="true"
    >

      <div class="modal-dialog modal-md">
        <div class="modal-content">
          <div class="modal-body">
            <div class="container py-5">
              <div class="row">
                <div class="bg-white rounded p-3 shadow">
                  <h4>Add a new book</h4>
                  <%= simple_form_for Book.new do |f| %>
                    <%= f.input :title %>
                    <%= f.input :year %>
                    <%= f.input :author %>
                    <%= f.input :overview %>
                    <%= f.input :genre %>
                    <%= f.submit class: "btn btn-success" %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- end of modal diallog -->
  </div>
  <!-- Cards to Show books -->
  <div class="container">

    <% @books.each_slice(3) do |book_row| %>
      <div class="row">
        <% book_row.each do |book| %>

          <div
            class="col-md-4"
            style="box-shadow: rgba(255, 255, 255, 0.1) 0px 1px 1px 0px inset, rgba(50, 50, 93, 0.25) 0px 50px 100px -20px, rgba(0, 0, 0, 0.3) 0px 30px 60px -30px;"
          >
            <div class="card mb-4">
              <div class="card-header"><%= image_tag book.poster_image, class: "card-img-top-small img-fluid" %></div>

              <div class="card-body">

                <h5 class="card-title"><%= book.title %></h5>
                <p class="card-text"><%= book.author %></p>
                <%= link_to "Read More", book_path(book), class: "btn btn-outline-success" %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>

  </div>
  <!-- end of showing books -->
</div>
<!--Add New Book Modal -->


</div>

<footer>
  <div class="cover-heading">
    <div class="socials-box">
      <div class="container ">
        <div class="row justify-content-center text-center py-4">
          <p class="my-font" style="letter-spacing: 1.5px; font-weight: 50px;">Follow Us</p>
          <p class="mb-0">
            <span class="icons-facebook">
              <i class="mr-1 fab fa-facebook-f">
                <span class="my-font">&nbsp; Facebook &nbsp; | &nbsp;
                </span>
              </i>
            </span>
            <span class="icons-instagram pl-3">
              <i class="mr-1 fab fa-instagram">
                <span class="my-font">&nbsp; Instagram</span>
              </i>
            </span>
          </p>
          <p
            class="my-font pt-3"
            style="font-size: 13px; font-weight: 50px; letter-spacing: 1px;"
          >Copyright &copy; The AirBnB Books Store</p>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/books/new.html.erb
<div class="container py-5">
   <div class="row">
      <div class="col-12 col-md-6 offset-lg-3">
         <div class="bg-white rounded p-3 shadow">
            <h4>Add a new book</h4>
            <%= simple_form_for @book do |f| %>
              <%= f.input :title %>
              <%= f.input :year %>
              <%= f.input :author %>
              <%= f.input :overview %>
              <%= f.input :genre %>
              <%= f.submit class: 'btn btn-success' %>
            <% end %>
         </div>
      </div>
   </div>
</div>

app/views/books/show.html.erb
<div class="container my-5">
  <%= image_tag @book.poster_image, class: "book-image" %>

  <div>
    <h1 class="book-start-one"><%= @book.title %></h1>
    <h2 class="book-start-two"><%= @book.author %></h2>
    <p class="book-start-three"><%= @book.year %></p>
    <p class="book-start-four">Overview: <%= @book.overview %></p>
    <p class="book-start-five">Genre: <%= @book.genre %></p>
  </div>

  <div class="formstyle">
    <%= simple_form_for [@book, @rental] do |f| %>
      <%= f.input :start_date, as: :string, input_html: { data: { controller: "datepicker", 'datepicker-dates-value': @existing_rental_dates.to_json } } %>
      <%= f.input :end_date, as: :string, input_html: { data: { controller: "datepicker", 'datepicker-dates-value': @existing_rental_dates.to_json } } %>
      <%= f.submit "Rent Me!", class: "text-decoration-none btn btn-outline-primary" , onclick: "Congratulations! Your rental was successful!" %>
    <% end %>
  </div>

  <%= link_to 'Back', root_path, class: 'btn btn-dark' %>
</div>

app/views/dashboards/index.html.erb
 <!-- Cards to Show my books -->

  <div class="container">
    <br>
        <h3 class="mb-0">My books</h3>
        <!-- <%= link_to "Add a new book", new_book_path(@book), class:"btn btn-outline-success" %> . -->
        <br>
    <% current_user.books.each_slice(3) do |book_row| %>
      <div class="row">
        <% book_row.each do |book| %>

          <div
            class="col-md-4"
            style="box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;">
            <div class="card mb-4">
              <div class="card-header"><%= image_tag book.poster_image, class: "card-img-top-small img-fluid" %></div>

              <div class="card-body">

                <h5 class="card-title"><%= book.title %></h5>
                <p class="card-text"><%= book.author %></p>
                 <i class="fa-regular fa-pen-to-square"></i>

                <%= link_to "Edit Book", edit_book_path(book), class: "text-decoration-none btn btn-outline-success" %>
                <br>
                <div class="rem-button-spacing mt-3">
                <i class="fa-solid fa-trash"></i>

                <%= link_to "Remove Book", book_path(book), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "text-decoration-none btn btn-outline-success" %>
                </div>

              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>

  </div>
  <!-- end of showing my books -->

  <!-- Cards to Show my Rentals -->

  <div class="container">
    <br/>

      <h3 class="mb-0">My Rentals</h3>
      <!-- <%= link_to "Add a new book", new_book_path(@book), class:"btn btn-outline-success" %> . -->
    <br/>
    <% current_user.rentals.each_slice(3) do |rental_row| %>
      <div class="row">
        <% rental_row.each do |rental| %>


          <div class="col-md-4" style="box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;">
            <div class="card mb-4">
              <div class="card-header"><%= image_tag rental.book.poster_image, class: "card-img-top-small img-fluid" %></div>

              <div class="card-body">
                <%= link_to rental.book.title, rental.book, class: "text-decoration-none text-black" %>
                <br>
                <%= rental.book.author %>
                <br>

                <div class="button-spacing mt-3">
                  <i class="fa-solid fa-trash"></i>
                  <%= link_to "Return Book", rental_path(rental), data: {turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "text-decoration-none btn btn-outline-success" %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
  <!-- end of showing my Rentals -->
</div>



<%
=begin%>

  <div class="container">
<br>
        <h3 class="mb-0">My books</h3>
        <!-- <%= link_to "Add a new book", new_book_path(@book), class:"btn btn-outline-success" %> . -->
<br>
    <% current_user.books.each_slice(3) do |book_row| %>
      <div class="row">
        <% book_row.each do |book| %>

          <div
            class="col-md-4"
            style="box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;">
            <div class="card mb-4">
              <div class="card-header"><%= image_tag "#{rand(1..10)}.jpg", class: "card-img-top-small img-fluid" %></div>

              <div class="card-body">

                <h5 class="card-title"><%= book.title %></h5>
                <p class="card-text"><%= book.author %></p>
                 <i class="fa-regular fa-pen-to-square"></i>

                <%= link_to "Edit Book", edit_book_path(book), class: "text-decoration-none btn btn-outline-success" %>
                <br>

                <i class="fa-solid fa-trash"></i>

                <%= link_to "Remove Book", book_path(book), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: "text-decoration-none btn btn-outline-success" %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>

  </div>
  <!-- end of showing my books -->

  <!-- Cards to Show my Rentals -->

  <div class="container">
     <br/>

        <h3 class="mb-0">My Rentals</h3>
        <!-- <%= link_to "Add a new book", new_book_path(@book), class:"btn btn-outline-success" %> . -->
     <br/>

    <% current_user.rentals.each_slice(3) do |rental_row| %>
      <div class="row">
        <% rental_row.each do |rental| %>

          <div
            class="col-md-4"
            style="box-shadow: rgba(100, 100, 111, 0.2) 0px 7px 29px 0px;">
            <div class="card mb-4">
              <div class="card-header"><%= image_tag "#{rand(1..10)}.jpg", class: "card-img-top-small img-fluid" %></div>

              <div class="card-body">

                <div class="pt-2">
    </div>

    <div class="rentals-container">
      <div class="d-flex align-align-text-center justify-content-between mb-5">
        <h3 class="mb-0">My rentals</h3>
      </div>

      <div class="card-container w-80 d-flex flex-wrap">
        <% current_user.rentals.each do |rental| %>
          <div class="co-12 col-sm-6 col-md-4 mb-3 pt-3">
            <div class="card-category">
              <%= image_tag "#{rand(1..10)}.jpg", class: "book-image" %>
              <br>
              <div class="pt-2">

<%
=end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirBnBooks</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>


  <!-- Include Bootstrap JS (and jQuery) -->
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
  </body>
</html>

app/views/profiles/index.html.erb
<div class="container mt-4 mb-4 p-3 d-flex justify-content-center">
  <div class="card card-profile p-4">
    <div class="image d-flex flex-column justify-content-center align-items-center">
        <%= cl_image_tag current_user.photo.key, width: 100 ,height: 100, class:"btn2 btn-secondary" %>
      <span class="name mt-3">
        <h2><%= current_user.first_name %></h2>
      </span>
      <span class="name mt-2">
        <h2><%= current_user.last_name %></h2>
      </span>
      <span class="idd">
        <p><%= current_user.email %></p>
      </span>
      <div class="d-flex flex-row justify-content-center align-items-center gap-2">
        <span class="idd1"></span>
      </div>
      <div class="d-flex flex-row justify-content-center align-items-center mt-3">
        <span class="number"> <span class="follow"></span></span> </div>

      <div class=" d-flex mt-2" >
          <%= link_to edit_user_registration_path do %>
          <button class="btn1 btn-dark">Edit Profile</button>
          <%end%>
      </div>

      <div class="text mt-3"> <span><%= current_user.first_name %> <%= current_user.last_name %> loves to rent a variety of different books!<br>
          <br>
            </span> </div>

      <div class="gap-3 mt-3 icons d-flex flex-row justify-content-center align-items-center"> <span><i class="fa fa-twitter"></i></span> <span><i class="fa fa-facebook-f"></i></span> <span><i class="fa fa-instagram"></i></span> <span><i class="fa fa-linkedin"></i></span> </div>

      <div class=" px-2 rounded mt-4 date "> <span class="join"></span> </div>
 </div>
 </div>
</div>

app/views/shared/_navbar.html.erb
 <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "airbnb-books-logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="row justify-content-center">
      <%= form_with url: root_path, method: :get, class: "d-flex" do %>
        <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              style: "width:620px",
              placeholder: "Title, Author, Genre, Keyword"
          %>
        <%= button_tag class: "btn btn-success" do %>
          <i class='fas fa-search'></i>
        <% end %>
      <% end %>
      <%# <div class="input-group">
        <div class="form-outline">
          <input id="search-input" type="search" class="form-control", placeholder= "Title, Author, Genre, Keyword">
        </div>
        <button id="search-button" type="button" class="btn btn-success" >
          <i class="fas fa-search"></i>
        </button>
      </div> %>
    </div>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Dashboard", dashboards_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar", alt: "dropdown menu" %>
            <% else %>
              <div class="dropdown menu" style="height:20px;width:20px;"></div>
            <% end %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Profile", profiles_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>

        <% end %>
      </ul>
    </div>
  </div>
</div>